import { Destination, TrainRoute, ProjectIssue } from './types';

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'es',
    country: 'España',
    countryCode: 'ES',
    flagEmoji: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Madrid', station: 'Madrid-Puerta de Atocha' },
      { name: 'Barcelona', station: 'Barcelona-Sants' },
      { name: 'Sevilla', station: 'Sevilla-Santa Justa' },
      { name: 'Valencia', station: 'València-Joaquín Sorolla' },
    ],
  },
  {
    id: 'fr',
    country: 'Francia',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'París', station: 'Paris-Gare de Lyon' },
      { name: 'Lyon', station: 'Lyon-Part-Dieu' },
      { name: 'Marsella', station: 'Marseille-Saint-Charles' },
      { name: 'Burdeos', station: 'Bordeaux-Saint-Jean' },
    ],
  },
  {
    id: 'de',
    country: 'Alemania',
    countryCode: 'DE',
    flagEmoji: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Berlín', station: 'Berlin Hauptbahnhof' },
      { name: 'Múnich', station: 'München Hbf' },
      { name: 'Fráncfort', station: 'Frankfurt (Main) Hbf' },
      { name: 'Hamburgo', station: 'Hamburg Hbf' },
    ],
  },
  {
    id: 'be',
    country: 'Bélgica',
    countryCode: 'BE',
    flagEmoji: '🇧🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Bruselas', station: 'Bruxelles-Midi / Brussel-Zuid' },
      { name: 'Brujas', station: 'Station Brugge' },
      { name: 'Gante', station: 'Gent-Sint-Pieters' },
      { name: 'Amberes', station: 'Antwerpen-Centraal' },
    ],
  },
  {
    id: 'uk',
    country: 'Reino Unido',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    cities: [
      { name: 'Londres', station: "London King's Cross" },
      { name: 'Edimburgo', station: 'Edinburgh Waverley' },
      { name: 'Manchester', station: 'Manchester Piccadilly' },
      { name: 'Birmingham', station: 'Birmingham New Street' },
    ],
  },
  {
    id: 'us',
    country: 'Estados Unidos',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    cities: [
      { name: 'Nueva York', station: 'New York Penn Station' },
      { name: 'Washington D.C.', station: 'Washington Union Station' },
      { name: 'Boston', station: 'Boston South Station' },
      { name: 'Filadelfia', station: '30th Street Station' },
    ],
  },
  {
    id: 'ca',
    country: 'Canadá',
    countryCode: 'CA',
    flagEmoji: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    cities: [
      { name: 'Toronto', station: 'Toronto Union Station' },
      { name: 'Montreal', station: 'Gare Centrale de Montréal' },
      { name: 'Ottawa', station: 'Ottawa Train Station' },
      { name: 'Quebec', station: 'Gare du Palais' },
    ],
  },
  {
    id: 'ru',
    country: 'Rusia',
    countryCode: 'RU',
    flagEmoji: '🇷🇺',
    currency: 'RUB',
    currencySymbol: '₽',
    cities: [
      { name: 'Moscú', station: 'Leningradsky Station' },
      { name: 'San Petersburgo', station: 'Moskovsky Glavny Station' },
      { name: 'Kazán', station: 'Kazan-Passazhirskaya' },
      { name: 'Nizhny Novgorod', station: 'Nizhny Novgorod Station' },
    ],
  },
  {
    id: 'cn',
    country: 'China',
    countryCode: 'CN',
    flagEmoji: '🇨🇳',
    currency: 'CNY',
    currencySymbol: '¥',
    cities: [
      { name: 'Pekín', station: 'Beijing South Railway Station' },
      { name: 'Shanghái', station: 'Shanghai Hongqiao' },
      { name: 'Guangzhou', station: 'Guangzhou South' },
      { name: 'Xi’an', station: 'Xi’an North' },
    ],
  },
  {
    id: 'in',
    country: 'India',
    countryCode: 'IN',
    flagEmoji: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    cities: [
      { name: 'Nueva Delhi', station: 'New Delhi Railway Station' },
      { name: 'Varanasi', station: 'Varanasi Junction' },
      { name: 'Mumbai', station: 'Chhatrapati Shivaji Maharaj Terminus' },
      { name: 'Jaipur', station: 'Jaipur Junction' },
    ],
  },
  {
    id: 'jp',
    country: 'Japón',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    cities: [
      { name: 'Tokio', station: 'Tokyo Station (東京駅)' },
      { name: 'Kioto', station: 'Kyoto Station (京都駅)' },
      { name: 'Osaka', station: 'Shin-Osaka Station (新大阪駅)' },
      { name: 'Hiroshima', station: 'Hiroshima Station (広島駅)' },
    ],
  },
];

export const INITIAL_TRAIN_ROUTES: TrainRoute[] = [
  // España
  {
    id: 'es-01',
    trainNumber: 'AVE 03102',
    operator: 'Renfe AVE',
    country: 'España',
    fromCity: 'Madrid',
    fromStation: 'Madrid-Puerta de Atocha',
    toCity: 'Barcelona',
    toStation: 'Barcelona-Sants',
    departureTime: '08:30',
    arrivalTime: '11:00',
    duration: '2h 30m',
    basePrice: 65,
    currency: 'EUR',
    trainModel: 'Talgo S-103 Alta Velocidad',
    availableSeatsCount: 42,
    amenities: ['Wi-Fi Gratuito', 'Toma de corriente', 'Coche cafetería', 'Silencio', 'Pantallas de entretenimiento'],
  },
  {
    id: 'es-02',
    trainNumber: 'OUIGO 06720',
    operator: 'Ouigo España',
    country: 'España',
    fromCity: 'Madrid',
    fromStation: 'Madrid-Puerta de Atocha',
    toCity: 'Barcelona',
    toStation: 'Barcelona-Sants',
    departureTime: '13:15',
    arrivalTime: '15:45',
    duration: '2h 30m',
    basePrice: 39,
    currency: 'EUR',
    trainModel: 'Alstom Euroduplex Doble Piso',
    availableSeatsCount: 58,
    amenities: ['Wi-Fi Ouigo Plus', 'Toma eléctrica', 'Cafetería a bordo'],
  },
  // Francia
  {
    id: 'fr-01',
    trainNumber: 'TGV 6605',
    operator: 'SNCF TGV inOui',
    country: 'Francia',
    fromCity: 'París',
    fromStation: 'Paris-Gare de Lyon',
    toCity: 'Lyon',
    toStation: 'Lyon-Part-Dieu',
    departureTime: '09:00',
    arrivalTime: '10:57',
    duration: '1h 57m',
    basePrice: 72,
    currency: 'EUR',
    trainModel: 'TGV Duplex 320 km/h',
    availableSeatsCount: 35,
    amenities: ['Wi-Fi TGV', 'Le Bar TGV', 'Asientos reclinables', 'Espacio equipaje'],
  },
  // Alemania
  {
    id: 'de-01',
    trainNumber: 'ICE 705',
    operator: 'Deutsche Bahn ICE',
    country: 'Alemania',
    fromCity: 'Berlín',
    fromStation: 'Berlin Hauptbahnhof',
    toCity: 'Múnich',
    toStation: 'München Hbf',
    departureTime: '07:05',
    arrivalTime: '11:15',
    duration: '4h 10m',
    basePrice: 85,
    currency: 'EUR',
    trainModel: 'ICE 4 Hochgeschwindigkeitszug',
    availableSeatsCount: 28,
    amenities: ['Bordrestaurant', 'WLAN gratis', 'Enchufes USB/220V', 'Zona Ruhebereich'],
  },
  // Bélgica
  {
    id: 'be-01',
    trainNumber: 'IC 1508',
    operator: 'SNCB InterCity',
    country: 'Bélgica',
    fromCity: 'Bruselas',
    fromStation: 'Bruxelles-Midi / Brussel-Zuid',
    toCity: 'Brujas',
    toStation: 'Station Brugge',
    departureTime: '10:23',
    arrivalTime: '11:18',
    duration: '0h 55m',
    basePrice: 16,
    currency: 'EUR',
    trainModel: 'SNCB Desiro ML',
    availableSeatsCount: 60,
    amenities: ['Climatización', 'Piso bajo accesible', 'Bicicletero'],
  },
  // Reino Unido
  {
    id: 'uk-01',
    trainNumber: 'AZUMA 1E09',
    operator: 'LNER Azuma',
    country: 'Reino Unido',
    fromCity: 'Londres',
    fromStation: "London King's Cross",
    toCity: 'Edimburgo',
    toStation: 'Edinburgh Waverley',
    departureTime: '11:00',
    arrivalTime: '15:20',
    duration: '4h 20m',
    basePrice: 78,
    currency: 'GBP',
    trainModel: 'Hitachi Class 800 Azuma',
    availableSeatsCount: 31,
    amenities: ['LNER Wi-Fi', 'Café Bar', 'Tomas en cada asiento', 'Vistas panorámicas'],
  },
  // USA
  {
    id: 'us-01',
    trainNumber: 'Acela 2150',
    operator: 'Amtrak Acela Express',
    country: 'Estados Unidos',
    fromCity: 'Nueva York',
    fromStation: 'New York Penn Station',
    toCity: 'Washington D.C.',
    toStation: 'Washington Union Station',
    departureTime: '06:45',
    arrivalTime: '09:40',
    duration: '2h 55m',
    basePrice: 120,
    currency: 'USD',
    trainModel: 'Amtrak Acela II High Speed',
    availableSeatsCount: 22,
    amenities: ['AmtrakConnect Wi-Fi', 'Café Car', 'Quiet Car', 'Asientos de cuero anchos'],
  },
  // Canadá
  {
    id: 'ca-01',
    trainNumber: 'VIA 64',
    operator: 'VIA Rail Canada',
    country: 'Canadá',
    fromCity: 'Toronto',
    fromStation: 'Toronto Union Station',
    toCity: 'Montreal',
    toStation: 'Gare Centrale de Montréal',
    departureTime: '09:20',
    arrivalTime: '14:25',
    duration: '5h 05m',
    basePrice: 94,
    currency: 'CAD',
    trainModel: 'Siemens Venture Trainset',
    availableSeatsCount: 39,
    amenities: ['Wi-Fi Onboard', 'Servicio de comida a bordo', 'Espacio para bicicletas'],
  },
  // Rusia
  {
    id: 'ru-01',
    trainNumber: 'Sapsan 758A',
    operator: 'RZD Sapsan Express',
    country: 'Rusia',
    fromCity: 'Moscú',
    fromStation: 'Leningradsky Station',
    toCity: 'San Petersburgo',
    toStation: 'Moskovsky Glavny Station',
    departureTime: '07:00',
    arrivalTime: '10:50',
    duration: '3h 50m',
    basePrice: 3400,
    currency: 'RUB',
    trainModel: 'Siemens Velaro RUS',
    availableSeatsCount: 45,
    amenities: ['Vagón Bistro', 'Mediacenter Wi-Fi', 'Tomas de 220V', 'Servicio de té'],
  },
  // China
  {
    id: 'cn-01',
    trainNumber: 'G1 Fuxing',
    operator: 'China Railway High-Speed',
    country: 'China',
    fromCity: 'Pekín',
    fromStation: 'Beijing South Railway Station',
    toCity: 'Shanghái',
    toStation: 'Shanghai Hongqiao',
    departureTime: '09:00',
    arrivalTime: '13:28',
    duration: '4h 28m',
    basePrice: 553,
    currency: 'CNY',
    trainModel: 'CR400AF Fuxing Hao 350 km/h',
    availableSeatsCount: 75,
    amenities: ['Wi-Fi 5G alta velocidad', 'Coche comedor', 'Tomas de carga rápida', 'Servicio de té caliente'],
  },
  // India
  {
    id: 'in-01',
    trainNumber: '22436 Vande Bharat',
    operator: 'Indian Railways',
    country: 'India',
    fromCity: 'Nueva Delhi',
    fromStation: 'New Delhi Railway Station',
    toCity: 'Varanasi',
    toStation: 'Varanasi Junction',
    departureTime: '06:00',
    arrivalTime: '14:00',
    duration: '8h 00m',
    basePrice: 1750,
    currency: 'INR',
    trainModel: 'Train 18 Vande Bharat Semi-High Speed',
    availableSeatsCount: 68,
    amenities: ['Comida incluida', 'Pantallas de info', 'Asientos giratorios 180°', 'Puertas automáticas'],
  },
  // Japón
  {
    id: 'jp-01',
    trainNumber: 'Nozomi 213',
    operator: 'JR Central Shinkansen',
    country: 'Japón',
    fromCity: 'Tokio',
    fromStation: 'Tokyo Station (東京駅)',
    toCity: 'Osaka',
    toStation: 'Shin-Osaka Station (新大阪駅)',
    departureTime: '08:00',
    arrivalTime: '10:25',
    duration: '2h 25m',
    basePrice: 14720,
    currency: 'JPY',
    trainModel: 'Shinkansen N700S Supreme 285 km/h',
    availableSeatsCount: 54,
    amenities: ['Shinkansen Free Wi-Fi', 'Enchufe individual', 'Servicio de carrito de bento', 'Extrema puntualidad'],
  },
];

export const INITIAL_ISSUES: ProjectIssue[] = [
  {
    id: 'ISSUE-01',
    number: 1,
    title: 'Configuración de Docker y Base de Datos MongoDB con Seed de 11 Países',
    conventionalCommit: 'chore(db): configurar contenedor MongoDB con persistencia y seed de 11 países',
    phase: 'Fase 1: Infraestructura y Datos',
    objective: 'Establecer el entorno Dockerizado con persistencia y precargar rutas de España, Francia, Alemania, Bélgica, UK, USA, Canadá, Rusia, China, India y Japón.',
    scopeIncluded: [
      'docker-compose.yml con servicio mongo:7.0 y volumen nombrado',
      'Script database/mongo-init.js con 11 países y más de 30 rutas de trenes',
      'Usuario administrador inicial (admin@railworld.com)',
    ],
    scopeExcluded: ['Creación de backend Express o FastAPI', 'Frontend'],
    acceptanceCriteria: [
      'docker compose up -d mongo levanta en <30s',
      'La colección trains tiene 33 rutas y destinations 11 países',
      'Los datos persisten tras reiniciar el contenedor',
    ],
    dependencies: ['Ninguna'],
    evidences: ['Captura de mongosh con conteo de documentos', 'Log de inicio de Docker'],
    status: 'approved',
    assignee: 'Ambos',
    prTitle: 'PR #1 - Configuración de MongoDB y datos iniciales',
  },
  {
    id: 'ISSUE-02',
    number: 2,
    title: 'Definición de Contratos de API REST (OpenAPI 3.0)',
    conventionalCommit: 'docs(api): diseñar especificación OpenAPI 3.0 para paridad Express-FastAPI',
    phase: 'Fase 1: Infraestructura y Datos',
    objective: 'Crear el contrato formal para garantizar 100% de paridad entre Express y FastAPI.',
    scopeIncluded: [
      'Esquema OpenAPI 3.0 en docs/openapi.yaml',
      'Tipado de los 12 endpoints (Auth, Trains, Seats, Bookings, Admin)',
    ],
    scopeExcluded: ['Código ejecutable de backend'],
    acceptanceCriteria: [
      'Validador OpenAPI aprueba el esquema sin advertencias',
      'Todos los códigos de error HTTP 400, 401, 403, 404, 500 están documentados',
    ],
    dependencies: ['Issue #01'],
    evidences: ['Captura de Swagger Editor sin errores'],
    status: 'approved',
    assignee: 'Integrante 1',
    prTitle: 'PR #2 - Especificación de OpenAPI 3.0',
  },
  {
    id: 'ISSUE-03',
    number: 3,
    title: 'Backend 1 (Express): Autenticación JWT y Roles de Usuario',
    conventionalCommit: 'feat(auth-express): implementar registro, login y middleware JWT en Node.js/Express',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Desarrollar autenticación con JWT, hasheo con bcrypt y control de roles (cliente y admin) en Node.js/Express.',
    scopeIncluded: [
      'POST /api/auth/register con validación de email único',
      'POST /api/auth/login con firma de JWT',
      'GET /api/auth/me con validación de cabecera Bearer',
      'Middleware de autorización por rol',
    ],
    scopeExcluded: ['Endpoints de trenes o reservas'],
    acceptanceCriteria: [
      'Contraseña guardada en hash bcrypt (10 rounds)',
      'Token JWT expira y protege rutas privadas',
      'Rechazo de email duplicado con 400 Bad Request',
    ],
    dependencies: ['Issue #01', 'Issue #02'],
    evidences: ['Peticiones Postman con JWT y registro de nuevo usuario'],
    status: 'completed',
    assignee: 'Integrante 1',
    prTitle: 'PR #3 - Módulo de autenticación en Express',
  },
  {
    id: 'ISSUE-04',
    number: 4,
    title: 'Backend 2 (FastAPI): Autenticación JWT con Paridad Total',
    conventionalCommit: 'feat(auth-fastapi): implementar registro, login y dependencias OAuth2/JWT en Python/FastAPI',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Replicar el módulo de autenticación en Python/FastAPI compartiendo la misma base de datos y formato de token.',
    scopeIncluded: [
      'Esquemas Pydantic y modelos Motor/PyMongo',
      'Mismos 3 endpoints /api/auth/register, /api/auth/login, /api/auth/me',
      'Interoperabilidad de JWT_SECRET con Express',
    ],
    scopeExcluded: ['Endpoints de trenes'],
    acceptanceCriteria: [
      'Un token creado por Express es aceptado por FastAPI y viceversa',
      'Respuestas JSON idénticas a Express',
    ],
    dependencies: ['Issue #02', 'Issue #03'],
    evidences: ['Swagger /docs interactivo de FastAPI y prueba cruzada de JWT'],
    status: 'completed',
    assignee: 'Integrante 2',
    prTitle: 'PR #4 - Módulo de autenticación en FastAPI',
  },
  {
    id: 'ISSUE-05',
    number: 5,
    title: 'Backend 1 (Express): Catálogo de Trenes, Búsqueda y Mapa de Asientos',
    conventionalCommit: 'feat(trains-express): implementar endpoints de destinos, búsqueda y mapa de asientos',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Permitir la consulta de trenes en los 11 países con filtros por fecha, país, ciudad y consulta de mapa de asientos.',
    scopeIncluded: [
      'GET /api/destinations',
      'GET /api/trains/search',
      'GET /api/trains/:id',
      'GET /api/trains/:id/seats (matriz de vagones con estado libre/ocupado)',
    ],
    scopeExcluded: ['Creación de reservas'],
    acceptanceCriteria: [
      'Búsqueda responde en <100ms',
      'Filtros por origen, destino y fecha funcionan correctamente',
      'El mapa de asientos refleja asientos libres y ocupados',
    ],
    dependencies: ['Issue #03'],
    evidences: ['Postman con respuestas JSON de búsqueda y mapa de asientos'],
    status: 'completed',
    assignee: 'Integrante 1',
    prTitle: 'PR #5 - Catálogo de trenes y búsqueda en Express',
  },
  {
    id: 'ISSUE-06',
    number: 6,
    title: 'Backend 2 (FastAPI): Catálogo de Trenes con Paridad de Endpoints',
    conventionalCommit: 'feat(trains-fastapi): implementar catálogo de trenes y endpoints de búsqueda en FastAPI',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Implementar los endpoints de catálogo y búsqueda de trenes en Python/FastAPI con paridad estricta.',
    scopeIncluded: [
      'Routers de trenes y destinos en FastAPI',
      'Misma lógica de cálculo de asientos ocupados',
    ],
    scopeExcluded: ['Creación de reservas'],
    acceptanceCriteria: [
      'Respuestas JSON con idénticas claves y tipos que Express',
      'Misma velocidad de respuesta y filtros soportados',
    ],
    dependencies: ['Issue #04', 'Issue #05'],
    evidences: ['Comparativa JSON Diff entre Express y FastAPI'],
    status: 'completed',
    assignee: 'Integrante 2',
    prTitle: 'PR #6 - Catálogo de trenes en FastAPI',
  },
  {
    id: 'ISSUE-07',
    number: 7,
    title: 'Backend 1 (Express): Reservas, Simulación de Pago y E-Ticket QR',
    conventionalCommit: 'feat(bookings-express): implementar creación de reservas, bloqueo de asientos y generación de QR',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Permitir a los usuarios reservar asientos, simular pagos y emitir billetes electrónicos con código QR verificable.',
    scopeIncluded: [
      'POST /api/bookings (bloqueo atómico de asientos)',
      'GET /api/bookings/my-bookings',
      'GET /api/bookings/:id (con QR DataURL)',
      'DELETE /api/bookings/:id (cancelación y liberación de asientos)',
    ],
    scopeExcluded: ['Frontend'],
    acceptanceCriteria: [
      'No permite reservar asientos ya ocupados',
      'Al cancelar una reserva se liberan inmediatamente los asientos',
      'El QR contiene el código de reserva y datos verificables',
    ],
    dependencies: ['Issue #05'],
    evidences: ['Captura de ticket generado y QR decodificado'],
    status: 'completed',
    assignee: 'Integrante 1',
    prTitle: 'PR #7 - Módulo de reservas y QR en Express',
  },
  {
    id: 'ISSUE-08',
    number: 8,
    title: 'Backend 2 (FastAPI): Reservas y QR con Paridad en Python',
    conventionalCommit: 'feat(bookings-fastapi): implementar reservas y generación de QR con paridad en FastAPI',
    phase: 'Fase 2: Backends (Express & FastAPI)',
    objective: 'Replicar el ciclo de reservas, cancelación y código QR en FastAPI.',
    scopeIncluded: [
      'Generación de QR con librería qrcode de Python',
      'Endpoints de reservas con validaciones Pydantic',
    ],
    scopeExcluded: ['Frontend'],
    acceptanceCriteria: [
      'Una reserva creada en FastAPI es legible y cancelable desde Express y viceversa',
    ],
    dependencies: ['Issue #06', 'Issue #07'],
    evidences: ['Prueba cruzada de persistencia de reservas'],
    status: 'completed',
    assignee: 'Integrante 2',
    prTitle: 'PR #8 - Módulo de reservas en FastAPI',
  },
  {
    id: 'ISSUE-09',
    number: 9,
    title: 'Frontend 1 (React): Plataforma Completa de Búsqueda, Asientos y E-Ticket',
    conventionalCommit: 'feat(frontend-react): implementar interfaz de búsqueda, mapa de asientos interactivo y e-ticket',
    phase: 'Fase 3: Frontends (React & Svelte)',
    objective: 'Construir la aplicación web completa en React 19 con selector de país, mapa de asientos, pasarela y e-ticket.',
    scopeIncluded: [
      'Buscador con banderas de los 11 países y estaciones',
      'Mapa interactivo de asientos por vagón',
      'Checkout con simulación de pago',
      'Generador y visualizador de E-Ticket con QR',
      'Sección "Mis Reservas" y cancelación',
      'Selector de backend activo (Express ↔ FastAPI)',
    ],
    scopeExcluded: ['Frontend en Svelte'],
    acceptanceCriteria: [
      '100% responsiva (móvil y escritorio)',
      'Funciona perfectamente al cambiar el backend entre Express y FastAPI',
    ],
    dependencies: ['Issue #07', 'Issue #08'],
    evidences: ['Demo funcional del flujo completo de reserva'],
    status: 'in_progress',
    assignee: 'Integrante 1',
    prTitle: 'PR #9 - Frontend completo en React',
  },
  {
    id: 'ISSUE-10',
    number: 10,
    title: 'Frontend 2 (Svelte): Paridad de Vistas y Flujo de Compra en Svelte 5',
    conventionalCommit: 'feat(frontend-svelte): implementar interfaz con paridad de vistas y estados en Svelte',
    phase: 'Fase 3: Frontends (React & Svelte)',
    objective: 'Desarrollar la aplicación idéntica en Svelte 5 con los mismos componentes, estilos y consumo de API.',
    scopeIncluded: [
      'Estructura de componentes en Svelte (.svelte)',
      'Mismas 5 vistas y diseño Tailwind CSS',
      'Consumo de los mismos endpoints REST',
    ],
    scopeExcluded: [],
    acceptanceCriteria: [
      'Mismo flujo de usuario y experiencia visual que en React',
      'Consume indistintamente Express o FastAPI',
    ],
    dependencies: ['Issue #09'],
    evidences: ['Comparativa visual lado a lado React vs Svelte'],
    status: 'planned',
    assignee: 'Integrante 2',
    prTitle: 'PR #10 - Frontend completo en Svelte',
  },
  {
    id: 'ISSUE-11',
    number: 11,
    title: 'Panel de Administración y Matriz de Pruebas Cruzadas 2x2',
    conventionalCommit: 'feat(admin-e2e): panel de gestión de trenes y validación de paridad cruzada',
    phase: 'Fase 4: Testing & Admin',
    objective: 'Permitir la gestión de trenes para administradores y validar las 4 combinaciones posibles de Frontend/Backend.',
    scopeIncluded: [
      'CRUD de rutas para rol admin',
      'Matriz de pruebas (React+Express, React+FastAPI, Svelte+Express, Svelte+FastAPI)',
    ],
    scopeExcluded: [],
    acceptanceCriteria: [
      'Un tren creado en admin se refleja en tiempo real en ambas apps',
      'Matriz de paridad 100% verificada',
    ],
    dependencies: ['Issue #10'],
    evidences: ['Tabla de matriz de pruebas completada'],
    status: 'planned',
    assignee: 'Ambos',
    prTitle: 'PR #11 - Panel Admin y verificación cruzada',
  },
  {
    id: 'ISSUE-12',
    number: 12,
    title: 'Docker Compose Global, Healthchecks y Manual de Entrega',
    conventionalCommit: 'chore(deploy): docker-compose orquestado con healthchecks y manual de entrega',
    phase: 'Fase 5: Despliegue y Cierre',
    objective: 'Configurar el despliegue orquestado de todo el stack en un solo comando y redactar el README de entrega.',
    scopeIncluded: [
      'docker-compose.yml con MongoDB, Express, FastAPI, React y Svelte',
      'README.md con instrucciones paso a paso para el profesor',
      'Métricas comparativas finales (latencia, bundle size)',
    ],
    scopeExcluded: [],
    acceptanceCriteria: [
      'docker compose up levanta todo el sistema en <2 minutos',
      'Todos los servicios muestran status healthy',
    ],
    dependencies: ['Issue #11'],
    evidences: ['Grabación de terminal levantando el stack completo'],
    status: 'planned',
    assignee: 'Ambos',
    prTitle: 'PR #12 - Docker Compose global y entrega final',
  },
];
