import type { Destination, TrainRoute } from './types';

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'es',
    country: 'España',
    countryCode: 'ES',
    flagEmoji: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Madrid', station: 'Madrid-Puerta de Atocha' },
      { name: 'Barcelona', station: 'Barcelona-Sants' },
      { name: 'Sevilla', station: 'Sevilla-Santa Justa' },
      { name: 'Valencia', station: 'València-Joaquín Sorolla' },
    ],
  },
  {
    id: 'fr',
    country: 'Francia',
    countryCode: 'FR',
    flagEmoji: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'París', station: 'Paris-Gare de Lyon' },
      { name: 'Lyon', station: 'Lyon-Part-Dieu' },
      { name: 'Marsella', station: 'Marseille-Saint-Charles' },
      { name: 'Burdeos', station: 'Bordeaux-Saint-Jean' },
    ],
  },
  {
    id: 'de',
    country: 'Alemania',
    countryCode: 'DE',
    flagEmoji: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Berlín', station: 'Berlin Hauptbahnhof' },
      { name: 'Múnich', station: 'München Hbf' },
      { name: 'Fráncfort', station: 'Frankfurt (Main) Hbf' },
      { name: 'Hamburgo', station: 'Hamburg Hbf' },
    ],
  },
  {
    id: 'be',
    country: 'Bélgica',
    countryCode: 'BE',
    flagEmoji: '🇧🇪',
    currency: 'EUR',
    currencySymbol: '€',
    cities: [
      { name: 'Bruselas', station: 'Bruxelles-Midi' },
      { name: 'Brujas', station: 'Station Brugge' },
      { name: 'Gante', station: 'Gent-Sint-Pieters' },
      { name: 'Amberes', station: 'Antwerpen-Centraal' },
    ],
  },
  {
    id: 'uk',
    country: 'Reino Unido',
    countryCode: 'GB',
    flagEmoji: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    cities: [
      { name: 'Londres', station: "London King's Cross" },
      { name: 'Edimburgo', station: 'Edinburgh Waverley' },
      { name: 'Manchester', station: 'Manchester Piccadilly' },
      { name: 'Birmingham', station: 'Birmingham New Street' },
    ],
  },
  {
    id: 'us',
    country: 'Estados Unidos',
    countryCode: 'US',
    flagEmoji: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    cities: [
      { name: 'Nueva York', station: 'New York Penn Station' },
      { name: 'Washington D.C.', station: 'Washington Union Station' },
      { name: 'Boston', station: 'Boston South Station' },
      { name: 'Filadelfia', station: '30th Street Station' },
    ],
  },
  {
    id: 'ca',
    country: 'Canadá',
    countryCode: 'CA',
    flagEmoji: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'CA$',
    cities: [
      { name: 'Toronto', station: 'Toronto Union Station' },
      { name: 'Montreal', station: 'Gare Centrale de Montréal' },
      { name: 'Ottawa', station: 'Ottawa Train Station' },
      { name: 'Quebec', station: 'Gare du Palais' },
    ],
  },
  {
    id: 'ru',
    country: 'Rusia',
    countryCode: 'RU',
    flagEmoji: '🇷🇺',
    currency: 'RUB',
    currencySymbol: '₽',
    cities: [
      { name: 'Moscú', station: 'Leningradsky Station' },
      { name: 'San Petersburgo', station: 'Moskovsky Glavny Station' },
      { name: 'Kazán', station: 'Kazan-Passazhirskaya' },
      { name: 'Nizhny Novgorod', station: 'Nizhny Novgorod Station' },
    ],
  },
  {
    id: 'cn',
    country: 'China',
    countryCode: 'CN',
    flagEmoji: '🇨🇳',
    currency: 'CNY',
    currencySymbol: '¥',
    cities: [
      { name: 'Pekín', station: 'Beijing South Railway Station' },
      { name: 'Shanghái', station: 'Shanghai Hongqiao' },
      { name: 'Guangzhou', station: 'Guangzhou South' },
      { name: 'Xi’an', station: 'Xi’an North' },
    ],
  },
  {
    id: 'in',
    country: 'India',
    countryCode: 'IN',
    flagEmoji: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    cities: [
      { name: 'Nueva Delhi', station: 'New Delhi Railway Station' },
      { name: 'Varanasi', station: 'Varanasi Junction' },
      { name: 'Mumbai', station: 'Chhatrapati Shivaji Maharaj Terminus' },
      { name: 'Jaipur', station: 'Jaipur Junction' },
    ],
  },
  {
    id: 'jp',
    country: 'Japón',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    cities: [
      { name: 'Tokio', station: 'Tokyo Station (東京駅)' },
      { name: 'Kioto', station: 'Kyoto Station (京都駅)' },
      { name: 'Osaka', station: 'Shin-Osaka Station (新大阪駅)' },
      { name: 'Hiroshima', station: 'Hiroshima Station (広島駅)' },
    ],
  },
];